### ISSUE TITLE
[Need support]: To add Healenium Dependency

### ISSUE THREAD

**Issue by jesussalatiel** [healenium/healenium-example-maven#12]
### Describe the problem

I tried to add the dependency but i am getting the following issue 
![Screenshot from 2022-06-19 14-01-53](https://user-images.githubusercontent.com/20656493/174496545-8716ee86-9b83-4fe3-9ac3-e462ea6e97b7.png)
![Screenshot from 2022-06-19 14-02-00](https://user-images.githubusercontent.com/20656493/174496547-352fdc7c-9ab2-4670-9fbb-4b287b4d3427.png)

### Healenium Proxy version

NA

### Healenium Backend version

3.2.4

### Selenium version

4.2.2

### Logs appeared during using Healenium

```shell
Unresolved dependency: 'junit:junit:jar:5.8.1'
```

**Comment by ElenaStepuro** [comment]
Hello @jesussalatiel This issue related to junit, not to healenium. Please, check your junit dependencies.
