### ISSUE TITLE
Plugin could not be resolved. Ensure the plugin's groupId, artifactId and version are present.  Additional information: Unable to resolve com.epam.healenium:hlm-report-mvn[Need support]: 

### ISSUE THREAD

**Issue by saikrishna446** [healenium/healenium-example-maven#13]
### Describe the problem

Plugin could not be resolved. Ensure the plugin's groupId, artifactId and version are present.

Additional information: Unable to resolve com.epam.healenium:hlm-report-mvn

### Healenium Proxy version

3.2.4

### Healenium Backend version

3.2.4

### Logs appeared during using Healenium

```shell
Plugin could not be resolved. Ensure the plugin's groupId, artifactId and version are present.

Additional information: Unable to resolve com.epam.healenium:hlm-report-mvn
```

**Comment by ElenaStepuro** [comment]
Hello @saikrishna446 Healenium-Back version 3.2.4 doesn't exist. The latest version is 3.2.2. Please, use this.
Also, could you send your pom.xml file with added plugin?

**Comment by saikrishna446** [comment]
Hi, actually we are unable to generate the healenium hlm-report. please see the below pom.xml

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>MavenHybridFramework</groupId>
	<artifactId>MavenHybridFramework</artifactId>
	<version>Mav</version>

	<profiles>
		<profile>
			<id>Smoke</id>

			<build>
				<pluginManagement>
					<plugins>
						<plugin>
							<groupId>com.epam.healenium</groupId>
							<artifactId>hlm-report-mvn</artifactId>
							<version>1.1</version>
							<executions>
								<execution>
									<id>hlmReport</id>
									<phase>compile</phase>
									<goals>
										<goal>initReport</goal>
									</goals>
								</execution>
								<execution>
									<id>hlmReportB</id>
									<phase>test</phase>
									<goals>
										<goal>buildReport</goal>
									</goals>
								</execution>
							</executions>
						</plugin>
						<plugin>
							<groupId>org.apache.maven.plugins</groupId>
							<artifactId>maven-surefire-plugin</artifactId>
							<version>3.0.0-M6</version>
							<configuration>
								<suiteXmlFiles>
									<suiteXmlFile>src/main/resources/testing1.xml</suiteXmlFile>
								</suiteXmlFiles>
							</configuration>
						</plugin>
						<plugin>
							<groupId>org.apache.maven.plugins</groupId>
							<artifactId>maven-compiler-plugin</artifactId>
							<version>3.8.1</version>
							<configuration>
								<source>11</source>
								<target>11</target>
							</configuration>
						</plugin>
					</plugins>
				</pluginManagement>
			</build>
		</profile>





		
	</profiles>

	<dependencies>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.1.4</version>
		</dependency>

		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>5.7.0</version>
		</dependency>
		
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<version>5.7.0</version>
			<scope>compile</scope>
		</dependency>
		
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-params</artifactId>
			<version>5.7.0</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>5.7.0</version>
			<scope>test</scope>
		</dependency>


		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.5</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>31.1-jre</version>
		</dependency>

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>5.2.2</version>
		</dependency>

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>5.2.2</version>
		</dependency>

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-scratchpad</artifactId>
			<version>5.2.2</version>
		</dependency>




		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml-schemas</artifactId>
			<version>4.1.2</version>
		</dependency>

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>openxml4j</artifactId>
			<version>1.0-beta</version>
		</dependency>

		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports</artifactId>
			<version>5.0.9</version>
		</dependency>

		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.11.0</version>
		</dependency>

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.12.0</version>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>6.9.0</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>6.9.0</version>
			<scope>test</scope>
		</dependency>

		
		<dependency>
			<groupId>tech.grasshopper</groupId>
			<artifactId>extentreports-cucumber6-adapter</artifactId>
			<version>2.9.0</version>
		</dependency>
		
		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>5.1.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.22</version>
		</dependency>


		
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured</artifactId>
			<version>4.5.1</version>
			<scope>test</scope>
		</dependency>

		
		<dependency>
			<groupId>com.epam.healenium</groupId>
			<artifactId>healenium-web</artifactId>
			<version>3.2.2</version>
		</dependency>


	</dependencies>
	<build>
		<plugins>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<encoding>UTF-8</encoding>
					<source>11</source>
					<target>11</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by ElenaStepuro** [comment]
@saikrishna446 please, set it under 'plugins' group not in 'pluginManagement'. Also, to generate the report tests should be run by maven command and if some tests fail the report will not appear in logs.
